<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        // Default factory test user (password auto-generated by factory)
        User::factory()->create([
            'name' => 'Test User',
            'email' => 'test@example.com',
        ]);

        // Deterministic demo login
        User::updateOrCreate(
            ['email' => 'demo@bookingyard.in'],
            [
                'name' => 'Demo User',
                'password' => bcrypt('password123'),
            ]
        );
    }
}
